### ISSUE TITLE
Node features

### ISSUE THREAD

**Issue by hljjjmssyh** [dm-thu/GraphSGAN#4]
![image](https://user-images.githubusercontent.com/24326757/66266920-e7cbb380-e85d-11e9-9657-55fc3cd0ff2a.png)
1. Is the feature of the nodes randomly initialized?
2. Is the feature of the nodes the same as self.embedding at the beginning?
3. Why node features are not updated during backpropagation？
Thank you!

**Comment by Sleepychord** [comment]
1.2. No, the features are independent vectors from inputs.
3. The embeddings are pre-trained by graph-embedding algorithms and not fine-tuned, for that the trainable parameters are already in the neural networks. 
Please read the paper for better understanding. Thank you~

**Comment by hljjjmssyh** [comment]
What I want to express is that the node features are defined according to the pre-trained node features and neighbor features of the nodes? At the same time, these features remain unchanged during the training process, just training the neural network. Thank you for your patience.

**Comment by Sleepychord** [comment]
Hi, features are from inputs (aka. dataset), so it is unchanged...
